version: '3.1'

services:

  postgres:
    image: postgres:13.2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    links:
      - postgres
    ports:
      - 8080:8080

  php:
    # build: ./php-container
    image: php:7.4-apache
    working_dir: /var/www/html
    restart: always
    volumes:
      - ./php-container/src:/var/www/html/
      - ./lumen-react:/var/www/html/lumen-react
      - ./lumen-graphql:/var/www/html/lumen-graphql
    ports:
      - 8000:80
      - 8001:443

volumes:
  pgdata:
