env:
  es2021: true
  node: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "prettier"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 12
  sourceType: module
  project: tsconfig.json
  tsconfigRoodDir: __dirname
plugins:
  - "@typescript-eslint"
rules:
  {
    "@typescript-eslint/no-explicit-any": ["warn", { "fixToUnknown": true }],
    "@typescript-eslint/no-inferrable-types": "warn",
    "@typescript-eslint/prefer-nullish-coalescing": "warn",
    "@typescript-eslint/prefer-optional-chain": "warn",
    "@typescript-eslint/prefer-enum-initializers": "warn",
    "@typescript-eslint/prefer-literal-enum-member": "error",
  }
