version: '3.1'

services:

  php:
    image: appsvc/php
    restart: always
    volumes:
      - ../lumen-react:/home/site/wwwroot/lumen-react
      - ../lumen-graphql:/home/site/wwwroot/lumen-graphql
    ports:
      - "8000:8000"
